"""Block 4 agent simulation tests with real LLM calls.

Verifies that Sonnet can generate complete HTML delivery when given
claims-compressed input (not raw 80KB results).

Requires: OPENROUTER_API_KEY environment variable.

Usage:
    OPENROUTER_API_KEY=sk-or-... pytest tests/integration/test_block4_simulation.py -x -q
"""

from __future__ import annotations

import json
import os
import time
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]


def get_api_key() -> str | None:
    return os.environ.get("OPENROUTER_API_KEY")


requires_api = pytest.mark.skipif(
    get_api_key() is None,
    reason="OPENROUTER_API_KEY not set",
)


def _load_session_data(
    results_path: str, knowledge_path: str, max_claims: int = 25
) -> tuple[str, list[dict], str]:
    """Load real session data for simulation."""
    results_file = ROOT / results_path
    knowledge_file = ROOT / knowledge_path

    knowledge = ""
    if knowledge_file.exists():
        knowledge = knowledge_file.read_text()[:4000]

    claims = []
    if results_file.exists():
        for line in results_file.read_text().strip().split("\n"):
            if not line.strip():
                continue
            r = json.loads(line)
            if r.get("metadata", {}).get("llm_relevant"):
                claims.append(
                    {
                        "url": r.get("url", ""),
                        "title": r.get("title", "")[:100],
                        "claim": r.get("snippet", "")[:200],
                        "source": r.get("source", ""),
                    }
                )
    claims = claims[:max_claims]

    citation_text = "\n".join(
        f"[{i}] {c['title']} — {c['url']}" for i, c in enumerate(claims, 1)
    )
    return knowledge, claims, citation_text


def _build_block4_prompt(
    topic: str,
    knowledge: str,
    claims: list[dict],
    citation_text: str,
    delivery_format: str = "Rich HTML",
    language: str = "English",
) -> str:
    return f"""You are AutoSearch, synthesizing a research report.

Topic: {topic}
Delivery format: {delivery_format}
Language: {language}
Content structure: Full Report

1. Blend the knowledge backbone with search discoveries
2. Organize by concept, not by source
3. Mark provenance: [knowledge] vs [discovered] vs [verified]
4. If Rich HTML: produce a standalone HTML file with tables, styling, and diagrams
5. If Markdown: produce a .md report
6. Report footer: "Generated by AutoSearch v2026.04.04.2"

KNOWLEDGE BACKBONE:
{knowledge}

CLAIMS ({len(claims)} relevant results, compressed):
{json.dumps(claims, ensure_ascii=False)[:5000]}

CITATION INDEX:
{citation_text}

Write the complete delivery now."""


def _call_sonnet(prompt: str, max_tokens: int = 16000) -> tuple[str, float]:
    """Call Sonnet via OpenRouter, return (content, elapsed_seconds)."""
    from openai import OpenAI

    client = OpenAI(
        base_url="https://openrouter.ai/api/v1",
        api_key=get_api_key(),
    )
    start = time.monotonic()
    response = client.chat.completions.create(
        model="anthropic/claude-sonnet-4-6",
        max_tokens=max_tokens,
        messages=[{"role": "user", "content": prompt}],
    )
    elapsed = time.monotonic() - start
    content = response.choices[0].message.content or ""
    return content, elapsed


# ── Fixtures for real session data ──────────────────────────────────

SESSIONS = {
    "medium": {
        "results": "evidence/20260404-ai-product-dev-trends-results.jsonl",
        "knowledge": "state/session-20260404-ai-product-dev-trends-knowledge.md",
        "topic": "AI product development trends 2026",
    },
    "large": {
        "results": "evidence/20260404-ai-native-game-2026-trends-results.jsonl",
        "knowledge": "state/session-20260404-ai-native-game-2026-trends-knowledge.md",
        "topic": "AI native game trends 2026",
    },
}


def _session_data_available(session_key: str) -> bool:
    s = SESSIONS[session_key]
    return (ROOT / s["results"]).exists() and (ROOT / s["knowledge"]).exists()


@requires_api
class TestBlock4HTMLGeneration:
    """Verify Sonnet generates complete HTML from claims-compressed input."""

    @pytest.mark.skipif(
        not _session_data_available("medium"),
        reason="Medium session data not available",
    )
    def test_medium_html_completes(self) -> None:
        """~50 results, Standard depth, Rich HTML — should complete < 5 min."""
        s = SESSIONS["medium"]
        knowledge, claims, citations = _load_session_data(
            s["results"], s["knowledge"], max_claims=20
        )
        prompt = _build_block4_prompt(s["topic"], knowledge, claims, citations)

        content, elapsed = _call_sonnet(prompt)

        assert elapsed < 300, f"Took {elapsed:.0f}s (> 5 min)"
        assert len(content) > 2000, f"Output too short: {len(content)} chars"
        assert "<html" in content.lower() or "<style" in content.lower(), (
            "No HTML output"
        )
        assert "AutoSearch" in content, "Missing footer"

    @pytest.mark.skipif(
        not _session_data_available("large"),
        reason="Large session data not available",
    )
    def test_large_html_completes(self) -> None:
        """120+ results (compressed to 25 claims), Deep, Rich HTML — must not hang."""
        s = SESSIONS["large"]
        knowledge, claims, citations = _load_session_data(
            s["results"], s["knowledge"], max_claims=25
        )
        prompt = _build_block4_prompt(
            s["topic"], knowledge, claims, citations, language="Chinese"
        )

        content, elapsed = _call_sonnet(prompt)

        assert elapsed < 480, f"Took {elapsed:.0f}s (> 8 min)"
        assert len(content) > 2000, f"Output too short: {len(content)} chars"
        assert "<html" in content.lower() or "<style" in content.lower(), (
            "No HTML output"
        )

    @pytest.mark.skipif(
        not _session_data_available("medium"),
        reason="Medium session data not available",
    )
    def test_markdown_completes(self) -> None:
        """Same data, Markdown format — should be faster and smaller."""
        s = SESSIONS["medium"]
        knowledge, claims, citations = _load_session_data(
            s["results"], s["knowledge"], max_claims=15
        )
        prompt = _build_block4_prompt(
            s["topic"],
            knowledge,
            claims,
            citations,
            delivery_format="Markdown",
        )

        content, elapsed = _call_sonnet(prompt, max_tokens=8000)

        assert elapsed < 180, f"Took {elapsed:.0f}s (> 3 min)"
        assert len(content) > 1000, f"Output too short: {len(content)} chars"
        assert "##" in content, "No Markdown headers"
