#!/usr/bin/env python3
"""Assemble a complete AutoSearch HTML report from body HTML + template.

Usage:
    python3 lib/assemble_html.py --body delivery/ID-body.html \
        --meta '{"topic":"...","version":"...","session_id":"...","date":"...","citations":N}' \
        --output delivery/ID.html

    python3 lib/assemble_html.py --body delivery/ID-body.html \
        --meta-file delivery/ID-meta.json \
        --output delivery/ID.html

The template is at lib/templates/report.html.  Body HTML should contain
semantic HTML using the template's CSS classes (card, badge-*, insight, etc.)
with <section id="..."> and <h2>/<h3> for TOC generation.
"""

from __future__ import annotations

import argparse
import html as html_stdlib  # noqa: F811 — shadows local `html` var in assemble()
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TEMPLATE_PATH = ROOT / "lib" / "templates" / "report.html"


def extract_toc(body: str) -> str:
    """Generate sidebar TOC nav entries from <section id> and <h2>/<h3> tags."""
    # Find all sections with id and their h2 text
    section_pattern = re.compile(
        r'<section[^>]*\bid=["\']([^"\']+)["\'][^>]*>.*?'
        r"<h2[^>]*>(.*?)</h2>",
        re.DOTALL,
    )

    entries: list[str] = []

    for match in section_pattern.finditer(body):
        section_id = match.group(1)
        h2_raw = match.group(2)
        # Strip HTML tags from h2 to get plain text
        h2_text = re.sub(r"<[^>]+>", "", h2_raw).strip()

        if not h2_text:
            continue

        entries.append(f'      <a href="#{section_id}">{h2_text}</a>')

    # Also find standalone <h2 id="..."> not inside sections
    h2_id_pattern = re.compile(
        r'<h2[^>]*\bid=["\']([^"\']+)["\'][^>]*>(.*?)</h2>', re.DOTALL
    )
    found_ids = {m.group(1) for m in section_pattern.finditer(body)}

    for match in h2_id_pattern.finditer(body):
        h2_id = match.group(1)
        if h2_id in found_ids:
            continue
        h2_text = re.sub(r"<[^>]+>", "", match.group(2)).strip()
        if h2_text:
            entries.append(f'      <a href="#{h2_id}">{h2_text}</a>')

    return "\n".join(entries) if entries else '      <a href="#">Report</a>'


def build_footer(meta: dict) -> str:
    """Build the footer HTML from metadata."""
    version = meta.get("version", "unknown")
    session_id = meta.get("session_id", "")
    date = meta.get("date", "")
    citations = meta.get("citations", 0)

    parts_left = [f"<strong>Generated by AutoSearch v{version}</strong>"]
    if session_id:
        parts_left.append(f"Session: {session_id}")
    if date:
        parts_left.append(date)

    left = " &nbsp;&middot;&nbsp; ".join(parts_left)

    parts_right = []
    if citations:
        parts_right.append(f"{citations} citations")
    right = " &nbsp;&middot;&nbsp; ".join(parts_right) if parts_right else ""

    lines = [f"      <div>{left}</div>"]
    if right:
        lines.append(f"      <div>{right}</div>")
    return "\n".join(lines)


def detect_lang(body: str) -> str:
    """Detect language from body content (Chinese vs English)."""
    chinese_chars = len(re.findall(r"[\u4e00-\u9fff]", body[:2000]))
    return "zh-CN" if chinese_chars > 50 else "en"


def assemble(body_path: Path, meta: dict, output_path: Path) -> None:
    """Read template, insert body/TOC/footer, write output."""
    if not TEMPLATE_PATH.exists():
        print(f"ERROR: Template not found at {TEMPLATE_PATH}", file=sys.stderr)
        sys.exit(1)

    template = TEMPLATE_PATH.read_text(encoding="utf-8")
    body = body_path.read_text(encoding="utf-8")

    title = meta.get("topic", "AutoSearch Report")
    lang = detect_lang(body)
    toc = extract_toc(body)
    footer = build_footer(meta)

    html = template
    html = html.replace("{{LANG}}", lang)
    html = html.replace("{{TITLE}}", html_stdlib.escape(title))
    html = html.replace("{{TOC}}", toc)
    html = html.replace("{{BODY}}", body)
    html = html.replace("{{FOOTER}}", footer)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(html, encoding="utf-8")
    print(f"Assembled: {output_path} ({len(html):,} bytes)")


def main() -> int:
    parser = argparse.ArgumentParser(description="Assemble AutoSearch HTML report")
    parser.add_argument("--body", required=True, help="Path to body HTML file")
    parser.add_argument("--meta", help="JSON string with metadata")
    parser.add_argument("--meta-file", help="Path to JSON metadata file")
    parser.add_argument("--output", required=True, help="Output HTML path")
    args = parser.parse_args()

    # Load metadata
    if args.meta_file:
        meta = json.loads(Path(args.meta_file).read_text())
    elif args.meta:
        meta = json.loads(args.meta)
    else:
        meta = {}

    body_path = Path(args.body)
    if not body_path.exists():
        print(f"ERROR: Body file not found: {body_path}", file=sys.stderr)
        return 1

    output_path = Path(args.output)
    assemble(body_path, meta, output_path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
