# Self-written, plan v2.3 § 4.5 (autosearch init minimal)
from pathlib import Path

import pytest
import yaml

import autosearch.init_runner as init_runner_module
from autosearch.init_runner import InitError, InitResult, InitRunner

_CONFIG_HEADER = "# autosearch config — generated by `autosearch init` (safe to edit)\n"


def _config_path(tmp_path: Path) -> Path:
    return tmp_path / ".autosearch" / "config.yaml"


def _default_providers() -> dict[str, bool]:
    return {
        "claude_code": True,
        "anthropic": False,
        "openai": True,
        "gemini": False,
    }


def test_check_python_allows_supported_version(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(init_runner_module.sys, "version_info", (3, 12, 0))

    InitRunner().check_python()


def test_check_python_raises_for_unsupported_version(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setattr(init_runner_module.sys, "version_info", (3, 10, 9))

    with pytest.raises(InitError, match="Detected Python 3.10.9") as exc_info:
        InitRunner().check_python()

    assert "rerun `autosearch init`" in str(exc_info.value)


def test_detect_providers_uses_env_and_path(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("ANTHROPIC_API_KEY", "test-anthropic")
    monkeypatch.delenv("OPENAI_API_KEY", raising=False)
    monkeypatch.setenv("GOOGLE_API_KEY", "test-google")
    monkeypatch.setattr(
        init_runner_module.shutil,
        "which",
        lambda command: "/usr/bin/claude" if command == "claude" else None,
    )

    detected = InitRunner().detect_providers()

    assert detected == {
        "claude_code": True,
        "anthropic": True,
        "openai": False,
        "gemini": True,
    }


def test_write_config_creates_expected_yaml(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    config_path = _config_path(tmp_path)
    monkeypatch.setattr(InitRunner, "config_path", lambda self: config_path)
    runner = InitRunner()

    written_path = runner.write_config(_default_providers())
    payload = written_path.read_text(encoding="utf-8")
    config = yaml.safe_load(payload)

    assert written_path == config_path
    assert payload.startswith(_CONFIG_HEADER)
    assert config == {
        "llm": {
            "priority": ["claude_code", "anthropic", "openai", "gemini"],
            "detected": _default_providers(),
        },
        "log_level": "INFO",
        "session_store": {"path": "~/.autosearch/sessions.db"},
    }


def test_write_config_merge_preserves_user_fields_and_updates_detected(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    config_path = _config_path(tmp_path)
    monkeypatch.setattr(InitRunner, "config_path", lambda self: config_path)
    runner = InitRunner()
    runner.write_config(_default_providers())

    edited_config = {
        "llm": {
            "priority": ["openai", "claude_code"],
            "detected": {
                "claude_code": False,
                "anthropic": False,
                "openai": False,
                "gemini": False,
            },
            "temperature": 0.2,
        },
        "log_level": "DEBUG",
        "session_store": {"path": "custom.db"},
        "extra_top_level": "keep-me",
    }
    config_path.write_text(
        _CONFIG_HEADER + yaml.safe_dump(edited_config, sort_keys=False),
        encoding="utf-8",
    )

    updated_providers = {
        "claude_code": False,
        "anthropic": True,
        "openai": True,
        "gemini": True,
    }

    runner.write_config(updated_providers, overwrite=False)
    merged = yaml.safe_load(config_path.read_text(encoding="utf-8"))

    assert merged["log_level"] == "DEBUG"
    assert merged["llm"]["priority"] == ["openai", "claude_code"]
    assert merged["llm"]["temperature"] == 0.2
    assert merged["llm"]["detected"] == updated_providers
    assert merged["session_store"]["path"] == "custom.db"
    assert merged["extra_top_level"] == "keep-me"


def test_write_config_overwrite_replaces_existing_config(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    config_path = _config_path(tmp_path)
    monkeypatch.setattr(InitRunner, "config_path", lambda self: config_path)
    runner = InitRunner()
    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(
        _CONFIG_HEADER
        + yaml.safe_dump(
            {
                "llm": {"priority": ["openai"], "detected": {"openai": True}},
                "log_level": "DEBUG",
                "extra_top_level": "remove-me",
            },
            sort_keys=False,
        ),
        encoding="utf-8",
    )

    runner.write_config(_default_providers(), overwrite=True)
    overwritten = yaml.safe_load(config_path.read_text(encoding="utf-8"))

    assert overwritten["log_level"] == "INFO"
    assert overwritten["llm"]["priority"] == ["claude_code", "anthropic", "openai", "gemini"]
    assert overwritten["llm"]["detected"] == _default_providers()
    assert overwritten["session_store"]["path"] == "~/.autosearch/sessions.db"
    assert "extra_top_level" not in overwritten


def test_run_returns_result(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
    config_path = _config_path(tmp_path)
    providers = _default_providers()
    runner = InitRunner()
    monkeypatch.setattr(InitRunner, "config_path", lambda self: config_path)
    monkeypatch.setattr(runner, "detect_providers", lambda: providers)

    result = runner.run(overwrite=False)

    assert isinstance(result, InitResult)
    assert result.python_ok is True
    assert result.providers == providers
    assert result.config_path == config_path
    assert result.warnings == []
    assert result.next_steps
    assert config_path.exists()
