# Self-written, plan v2.3 § 4.5 (autosearch init minimal)
import os
import shutil
import sys
from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

_PROVIDER_ORDER = ["claude_code", "anthropic", "openai", "gemini"]
_CONFIG_HEADER = "# autosearch config — generated by `autosearch init` (safe to edit)\n"


class InitError(RuntimeError):
    """Raised when `autosearch init` cannot complete safely."""


@dataclass(frozen=True)
class InitResult:
    python_ok: bool
    providers: dict[str, bool]
    config_path: Path
    warnings: list[str]
    next_steps: list[str]


class InitRunner:
    def check_python(self) -> None:
        version_info = sys.version_info
        current_version = f"{version_info[0]}.{version_info[1]}.{version_info[2]}"
        if tuple(version_info[:2]) < (3, 12):
            raise InitError(
                "AutoSearch requires Python 3.12 or newer. "
                f"Detected Python {current_version}. "
                "Install Python 3.12+ and rerun `autosearch init`."
            )

    def detect_providers(self) -> dict[str, bool]:
        return {
            "claude_code": shutil.which("claude") is not None,
            "anthropic": bool(os.getenv("ANTHROPIC_API_KEY")),
            "openai": bool(os.getenv("OPENAI_API_KEY")),
            "gemini": bool(os.getenv("GOOGLE_API_KEY")),
        }

    def config_path(self) -> Path:
        return Path.home() / ".autosearch" / "config.yaml"

    def write_config(
        self,
        providers: dict[str, bool],
        *,
        overwrite: bool = False,
    ) -> Path:
        path = self.config_path()
        path.parent.mkdir(parents=True, exist_ok=True)

        config = self._default_config(providers)
        if path.exists() and not overwrite:
            existing = self._load_existing_config(path)
            config = self._merge_config(existing, providers)

        payload = _CONFIG_HEADER + yaml.safe_dump(config, sort_keys=False)
        path.write_text(payload, encoding="utf-8")
        return path

    def run(self, overwrite: bool) -> InitResult:
        self.check_python()
        providers = self.detect_providers()
        config_path = self.write_config(providers, overwrite=overwrite)

        warnings: list[str] = []
        next_steps = [
            "Run `autosearch doctor` to verify channel availability.",
            "Run `autosearch mcp-check` to verify MCP tools registered for your Agent.",
        ]

        if not any(providers.values()):
            warnings.append(
                "No LLM provider detected. Set ANTHROPIC_API_KEY, OPENAI_API_KEY, "
                "GOOGLE_API_KEY, or install the `claude` CLI."
            )
            next_steps.insert(
                0,
                "Add an API key or install the `claude` CLI, then rerun `autosearch init`.",
            )
        else:
            next_steps.insert(
                0,
                "Review `~/.autosearch/config.yaml` if you want to change `llm.priority`.",
            )

        return InitResult(
            python_ok=True,
            providers=providers,
            config_path=config_path,
            warnings=warnings,
            next_steps=next_steps,
        )

    def _default_config(self, providers: dict[str, bool]) -> dict[str, Any]:
        return {
            "llm": {
                "priority": list(_PROVIDER_ORDER),
                "detected": {name: providers[name] for name in _PROVIDER_ORDER},
            },
            "log_level": "INFO",
            "session_store": {
                "path": "~/.autosearch/sessions.db",
            },
        }

    def _load_existing_config(self, path: Path) -> dict[str, Any]:
        try:
            raw_config = yaml.safe_load(path.read_text(encoding="utf-8"))
        except yaml.YAMLError as exc:
            raise InitError(
                f"Existing config at {path} is not valid YAML. "
                "Fix it or rerun with `autosearch init --overwrite`."
            ) from exc

        if raw_config is None:
            return {}
        if not isinstance(raw_config, Mapping):
            raise InitError(
                f"Existing config at {path} must be a YAML mapping. "
                "Fix it or rerun with `autosearch init --overwrite`."
            )
        return dict(raw_config)

    def _merge_config(
        self,
        existing: dict[str, Any],
        providers: dict[str, bool],
    ) -> dict[str, Any]:
        merged = dict(existing)

        llm_value = merged.get("llm")
        llm_config = dict(llm_value) if isinstance(llm_value, Mapping) else {}
        llm_config.setdefault("priority", list(_PROVIDER_ORDER))
        llm_config["detected"] = {name: providers[name] for name in _PROVIDER_ORDER}
        merged["llm"] = llm_config

        merged.setdefault("log_level", "INFO")

        session_store_value = merged.get("session_store")
        session_store = (
            dict(session_store_value) if isinstance(session_store_value, Mapping) else {}
        )
        session_store.setdefault("path", "~/.autosearch/sessions.db")
        merged["session_store"] = session_store

        return merged
